### ISSUE TITLE
Sqlite wallet: pool timed out while waiting for an open connection

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-askar#115]
While working with the toolbox plugin for ACA-Py (specifically moving it to using Askar by default instead of Indy), we've started encountering errors like these in our integration tests when using a sqlite Askar store:

```
agent_1  | Traceback (most recent call last):
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/storage/askar.py", line 90, in get_record
agent_1  |     record_type, record_id, for_update=for_update
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_askar/store.py", line 421, in fetch
agent_1  |     self._handle, category, name, for_update
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_askar/bindings/__init__.py", line 225, in session_fetch
agent_1  |     return_type=EntryListHandle,
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_askar/bindings/lib.py", line 355, in invoke_async
agent_1  |     name, argtypes, *args, return_type=return_type
agent_1  |   File "/usr/local/lib/python3.7/asyncio/futures.py", line 263, in __await__
agent_1  |     yield self  # This tells Task to wait for completion.
agent_1  |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
agent_1  |     future.result()
agent_1  |   File "/usr/local/lib/python3.7/asyncio/futures.py", line 181, in result
agent_1  |     raise self._exception
agent_1  | aries_askar.error.AskarError: Backend error
agent_1  | Caused by: pool timed out while waiting for an open connection
agent_1  |
agent_1  | The above exception was the direct cause of the following exception:
agent_1  |
agent_1  | Traceback (most recent call last):
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 537, in connections_create_invitation
agent_1  |     mediation_id=mediation_id,
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 132, in create_invitation
agent_1  |     or_default=True,
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/connections/util.py", line 28, in mediation_record_if_id
agent_1  |     mediation_record = await MediationManager(profile).get_default_mediator()
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py", line 356, in get_default_mediator
agent_1  |     mediation_id = await self._get_default_mediator_id(session)
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py", line 342, in _get_default_mediator_id
agent_1  |     default_record = await self._get_default_record(session)
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py", line 326, in _get_default_record
agent_1  |     record_id=self.DEFAULT_MEDIATOR_RECORD_TYPE,
agent_1  |   File "/usr/src/app/.venv/lib/python3.7/site-packages/aries_cloudagent/storage/askar.py", line 93, in get_record
agent_1  |     raise StorageError("Error when fetching storage record") from err
agent_1  | aries_cloudagent.storage.error.StorageError: Error when fetching storage record
```

This is using Askar 0.2.7 and ACA-Py 0.7.4. Integration test run can be found [here](https://github.com/hyperledger/aries-acapy-plugin-toolbox/actions/runs/4367250591/jobs/7638468547) with logs printed from ACA-Py visible in the `Print logs on failure` task.

I'm mostly just lost on where to start digging into this issue. When I run our integration tests, it seems to work locally initially. In github actions, it seems to immediately fail. Also willing to accept that this likely isn't an issue with Askar or even ACA-Py. Any direction or advice would be appreciated.

**Comment by dbluhm** [comment]
cc @anwalker293

**Comment by genaris** [comment]
Could it be related to https://github.com/hyperledger/aries-askar/issues/109? Until the very recent fix merged yesterday (https://github.com/hyperledger/aries-askar/pull/114), Askar was defaulting the maximum number of connections for SQLite databases to the number of CPUs in the system.

If you are running in an Android emulator like me or a cloud environment with a single vCPU, most likely you'l have 1 connection at most which is already taken by the session object opened when a profile/wallet is opened.

You can override this by specifying manually the "max_connections" parameter in the store URI. Not sure if ACA-Py has exposed that to the Wallet Config objects but better modyfing py scripts than compiling a new binary :rofl:

**Comment by dbluhm** [comment]
Thanks for the pointers, @genaris! I'll do some digging. I'll see if ACA-Py permits setting max connections for sqlite (I know it does for Postgres, just not sure if it's exposed the same way).

**Comment by dbluhm** [comment]
I think we've identified the issue: long ago, back when profiles and sessions were being introduced to ACA-Py, we erroneously started opening sessions and then didn't explicitly close them in the toolbox plugin. This didn't have noticeable detrimental effects on Indy but clearly is a problem for Askar. We'll clean up our usage of these sessions. I'll close this issue for now; thanks for the help :slightly_smiling_face:
