### ISSUE TITLE
[React Native] Invalid character in iOS bundle identifier

### ISSUE THREAD

**Issue by AlexanderShenshin** [hyperledger/aries-askar#133]
There is an error on validation of iOS app bundle archived for Testflight upload:

```
This bundle is invalid. The bundle at path Payload/AppName.app/Frameworks/aries_askar.framework has an invalid
CFBundleldentifier 'org.hyperledger.aries_askar' There are invalid characters (characters that are not dots, hyphen and alphanumerics)
that have been replaced with their code point 'org.hyperledger.aries\u005faskar' CFBundleldentifier must be present, must contain
only alphanumerics, dots, hyphens and must not end with a dot.
```

The reason is `_` character in `org.hyperledger.aries_askar` identifier.

It's possible to work around this by updating local `Info.plist` file at `node_modules/@hyperledger/aries-askar-react-native/native/mobile/ios/aries_askar.xcframework/ios-arm64/aries_askar.framework`:

```
<key>CFBundleIdentifier</key>
<string>org.hyperledger.ariesaskar</string>
// "_" character was removed
```

Just to clarify, local build and runtime functionality are not affected by this - it's related to Apple validation rules for app distribution.

Such problem is also relevant for `indy-vdr` RN package.

**Comment by swcurran** [comment]
@blu3beri — can you take this and issues #134 and #135?  They seem to be related.
