### ISSUE TITLE
Add support for SSL/TLS

### ISSUE THREAD

**Issue by MonolithicMonk** [hyperledger/aries-askar#138]
Feature Request:  Add support for SSL/TLS

Why: So that applications can secure the communication between askar and the storage backend by encrypting the communication with tls certificates

It is entirely possible that I have missed the security model of askar and askar already encrypts this communication in a way that make TLS encryption redundant.  If this is the case please advise and I will propose a pull request to include the information in the aries cloudagent python documentation.

Also from a security audit perspective it will also help future auditors to access the strength of askar's security.

**Comment by andrewwhitehead** [comment]
This ought to be tested and documented, but it should also be possible to add the parameters to the connection string as Askar passes through options it doesn't recognize. The possible parameters are `sslmode`, `sslcert`, `sslrootcert`, and `sslkey`:

https://github.com/launchbadge/sqlx/blob/afb6b1066e61f8e3875f530d96cfb5a299f13fda/sqlx-postgres/src/options/parse.rs#L48-L58
