### ISSUE TITLE
How should work Scan?

### ISSUE THREAD

**Issue by rusfearuth** [hyperledger/aries-askar#16]
Hey! I'm trying to realise how the scan works. I thought that the scan is functionality which allows to retrieve data by page from the backend with special offset and limits.

How I understand of the scan behaviour:
We have some data in the backend. For instance, we have 5 records. I want to extract all data by 2 records 3 times.
```
// Algorithm

1. Create a new scan with the offset 0 and the limit 2
2. Call scan's next method and get first bunch of data with size 2
3. Call scan's next method and get second bunch of data with size 2
4. Call scan's next method and get third bunch of data with size 1
5. Close scan
```

Right know, the scan returns only the first bunch of data on calling the next. When you try to call the next again, you will get an invalid handler pointer. Is it okay behaviour or not? I'm asking because I couldn't find answer for my question in tests and documentation too.

Thx.

**Comment by rusfearuth** [comment]
I use my own, but it wraps the C calls as Python implementation.

It will be nice to get complex sample of using scan from your side.

**Comment by rusfearuth** [comment]
I'm using the Kotlin implementation. Thx for answer!

Will it be possible to change page size in future?

**Comment by rusfearuth** [comment]
> Are you using Python or something else? It's not clear.
> 
> The limit applies to the entire scan, not the size of the pages returned by next (that is currently fixed at 32).

Are you sure about 32? Based on code I can see that the page size depends on device CPU arch (https://doc.rust-lang.org/std/primitive.usize.html). You are using there `usize`.

https://github.com/hyperledger/aries-askar/blob/2ab2e5049df5f1f5fab06b91faa2f441b80ee620/src/storage/entry.rs#L475

**Comment by andrewwhitehead** [comment]
The two sqlite and postgres backends currently use this constant for the page size: https://github.com/hyperledger/aries-askar/blob/a93ce8d3f561eb86ce5a2cb497239bc274a7049f/src/backend/db_utils.rs#L23

It could be added to the interface when creating a Scan, but that would be a minor breaking change to the API. Is there a reason why you are using such a small number?

`askar_scan_next` will return an EntryListHandle of `0` when the end of the list is reached, which is probably why you are getting the invalid handle error.

**Comment by rusfearuth** [comment]
> The two sqlite and postgres backends currently use this constant for the page size:
> 
> https://github.com/hyperledger/aries-askar/blob/a93ce8d3f561eb86ce5a2cb497239bc274a7049f/src/backend/db_utils.rs#L23
> 
> It could be added to the interface when creating a Scan, but that would be a minor breaking change to the API. Is there a reason why you are using such a small number?
> 
> `askar_scan_next` will return an EntryListHandle of `0` when the end of the list is reached, which is probably why you are getting the invalid handle error.

No no. I don't need so small number at all. I just used 2 as an example. I thought that the limit is a page size. Now everything is clear for me.

The issue can be closed. Thx a lot!
