### ISSUE TITLE
Askar different import/export capability

### ISSUE THREAD

**Issue by MaticDiba** [hyperledger/aries-askar#18]
Using Aries Askar with Aries cloud agent, we would like to support the export of the wallet for possible backup/restore flows.

Is there any work planned to support:
- export of the whole database
- export of a single profile

**Comment by andrewwhitehead** [comment]
To avoid defining an ad-hoc storage format for the wallet, I would prefer to have it just stream records to a SQLite wallet and use that as the export format. Something like the [universal wallet spec](https://w3c-ccg.github.io/universal-wallet-interop-spec/) is higher-level and would need to be implemented by an application that is using Askar as a storage backend.

It should be possible to add a method to a Store instance to copy all data from another Store instance, or from a specific profile. If SQLite wasn't desired as the archival format then another backend could be added and used as the target.

**Comment by esune** [comment]
Relates to #82
