### ISSUE TITLE
Plaintext profile keys are stored in the database

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-askar#19]
When the default profile is created, the profile key is encrypted using the store key, but when creating a new profile in the same store, the profile key is stored in the database in a plaintext format https://github.com/hyperledger/aries-askar/blob/2ab2e5049df5f1f5fab06b91faa2f441b80ee620/src/backend/postgres/mod.rs#L115

As a consequence, loading of all profiles fails (except for the default one), since in the `resolve_profile_key` function, plaintext key is being decrypted https://github.com/hyperledger/aries-askar/blob/2ab2e5049df5f1f5fab06b91faa2f441b80ee620/src/backend/postgres/mod.rs#L594

[A connected issue is in the SQL query](https://github.com/hyperledger/aries-askar/blob/main/src/backend/postgres/mod.rs#L588) `SELECT id, profile_key FROM profiles WHERE name=?1` `?1` should be replaced with `$1`, otherwise the value is not bound correctly 

This issue is connected to [ ACA-py improved multitenancy implementation](https://github.com/hyperledger/aries-cloudagent-python/issues/1349) and represents a security vulnerability.

**Comment by andrewwhitehead** [comment]
I've got fixes for these issues lined up if you'd like to test that PR. I'm going to look at adding postgres to the CI before merging it.
