### ISSUE TITLE
[Question] Does Askar generate the same key to IndySDK ?

### ISSUE THREAD

**Issue by conanoc** [hyperledger/aries-askar#190]
I wonder if `LocalKey::from_seed(KeyAlg::Ed25519, seed, None)` and `create_and_store_my_did(<config with the same seed>)` generate the same key.
Askar's LocalKey is using `RandomDet::new(seed)` for rng, but I cannot figure out what Indy SDK is using.

**Comment by swcurran** [comment]
@andrewwhitehead — can you answer this one?

**Comment by conanoc** [comment]
I've tested with `LocalKey::from_secret_bytes(KeyAlg::Ed25519, seed)` and it generates the same key as `create_and_store_my_did(<config with the same seed>)`. Thanks @TimoGlastra
