### ISSUE TITLE
Auto deleting records from wallet based on expiry_ms.

### ISSUE THREAD

**Issue by dheerajbudhiraja** [hyperledger/aries-askar#206]
We have "expiry_ms" in wallet records, which is right now used to filter out expired records In perform_scan.

But I don't  see any provision to auto delete records after expiry time, this can lead to increase in wallet size in long term.

Is there any work going to auto delete or it is supposed to be handled from Aries agent side? 

If it needs to be handled in Aries agent, then also we will be needing perform_scan query to return back expired records also which are being filtered out.

**Comment by swcurran** [comment]
@andrewwhitehead — can you respond to this please?

AFAIK — the deletion of records in Aries Askar should be intiated by the Aries agent.  That said, I don’t know where the “expiry_ms” entry comes from and what it is intended to be used for. What sets that data item?

**Comment by joyride9999** [comment]
i think that expiry_ms is just to make sure that a query to db returns in a given amount of time ! And not to autodelete rows after an amount of time

**Comment by swcurran** [comment]
Hopefully that answers the question.  Closing this — feel free to ask for additional details.
