### ISSUE TITLE
Any approach to get more performant secrets/nonces generation?

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/aries-askar#21]
As i can see the only rng provided by `askar-crypto` is `OsRng` that is unacceptable slow (and potentially blocking) for a lot of use cases.

In my experience OsRng is often used only to seed pseudo-random rng (like ChaCha) with state cache in thread local storage.  Sure it can't be a good solution for `no std`, but what if we expose `thread_rng` or something similar as a dedicated feature?

**Comment by andrewwhitehead** [comment]
I don't think it would be difficult to add a flag to make thread_rng the default RNG, but it would require std support. I think all the places that use the default RNG also have a method to accept a custom RNG. I'm not sure what use cases would be impacted by the performance difference there.

**Comment by vimmerru** [comment]
> I think all the places that use the default RNG also have a method to accept a custom RNG.

I don't think so. Examples `fill_random`, `random_secret`, `random_nonce`.

**Comment by andrewwhitehead** [comment]
Those are all utility methods, there are simple workarounds. In any case I've added the `std_rng` flag (implied by `std`) in #23  which makes thread_rng the default. It does seem faster.
