### ISSUE TITLE
DB2 Support

### ISSUE THREAD

**Issue by scottexton** [hyperledger/aries-askar#269]
Askar currently only supports SqlLite and Postgres, but we also need support for DB2.  If I was to create a DB2 storage implementation would the code changes be accepted back into the project?  

I realise that the SqlLite and Postgres implementation currently use the Rust sqlx API - however, there is no DB2 support in the sqlx API (although there is a DB2 Rust driver available) - would this be a blocker for the DB2 implementation?

Thanks.

**Comment by swcurran** [comment]
Thoughts @andrewwhitehead ?
