### ISSUE TITLE
Able to create an in-memory sqlite database?

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-askar#318]
From the python library is there a way to create an in-memory sqlite database?

I see this https://github.com/hyperledger/aries-askar/blob/main/askar-storage/src/backend/sqlite/provision.rs#L50 and will try and figure it out myself. Just posting this here is anyone knows off the to of their head.

***context:*** We're trying to rely on askar fully in aca-py and remove the existing in-memory wallet that was created for testing. Having the option to create an in-memory wallet that is askar based would really help speed up the tests and prevent file IO errors.

**Comment by andrewwhitehead** [comment]
Yes, just use the store URL `sqlite://:memory:`.
