### ISSUE TITLE
Documentation for secure storage

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-askar#34]
This should include the abstract database schema (details vary between backends) and the encryption and decryption processes.

**Comment by yunxi-zhang** [comment]
Any updates on this task @andrewwhitehead ?

**Comment by swcurran** [comment]
Hey @andrewwhitehead -- did this work get done?  I recall you've been working on this.  Thanks!

**Comment by andrewwhitehead** [comment]
Closed by #37
