### ISSUE TITLE
Release Aries Askar for React Native to NPM

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-askar#67]
Continuation of https://github.com/hyperledger/aries-askar/issues/64, but focuses on the React Native implementation

The iOS & Android build is currently broken and needs some extra work.

TODO
- [ ] add iOS & Android build (CI pipeline)
- [ ] Fix react native setup

This doesn't include the NPM release setup, it just means making the react native package ready for release, and making sure the ios and android binaries can be built

**Comment by blu3beri** [comment]
Just tried to compile it for android and `aarch64-linux-android` works without a special environment. Have not tested iOS yet, but it does not seem to depend on `cmake-rs` which definitely is a plus. 

Android pipeline can be copied from here: https://github.com/blu3beri/indy-vdr/actions/runs/3568557521/workflow
