### ISSUE TITLE
[JS Wrapper] Custom error thrown when no entries found

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-askar#77]
There are certain use cases where Askar JS is throwing a custom error (code 100) when I think it would be more appropriate to throw a specific error. These are the cases I've found during an initial integration with aries-framework-javascript:

- **Session.fetch** and no entry has been found (should be NotFound or simply return undefined, as current API suggests)
- **Session.fetchKey** and no entry has been found (should be NotFound as current API suggests)
- **Scan.fetchAll**/Session.fetchAllKeys and no entries matching the query have been found (should be NotFound or simply return an empty array)

**Comment by TimoGlastra** [comment]
This is fixed by https://github.com/hyperledger/aries-askar/pull/111
